apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-details-service
  labels:
    app: product-details-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-details-service
  template:
    metadata:
      labels:
        app: product-details-service
    spec:
      containers:
        - name: product-details-service
          image: lmo2914/product-details-service:latest # Docker Hub 사용자명과 서비스이름을 입력해주세요.
          env:
            - name: MODE
              value: "kubernetes" 
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 5001
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 5001
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: product-details-service-svc
  labels:
    app: product-details-service
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: product-details-service
